export {
  useChangeAdminScenarioStatusMutation,
  useChangeAdminTopicStatusMutation,
  useCreateAdminQuizOptionMutation,
  useCreateAdminQuizQuestionMutation,
  useCreateAdminScenarioMutation,
  useCreateAdminScenarioOptionMutation,
  useCreateAdminScenarioStepMutation,
  useCreateAdminTheoryBlockMutation,
  useCreateAdminTopicMutation,
  useDeleteAdminQuizOptionMutation,
  useDeleteAdminQuizQuestionMutation,
  useDeleteAdminScenarioOptionMutation,
  useDeleteAdminScenarioStepMutation,
  useDeleteAdminTheoryBlockMutation,
  useGetAdminScenariosQuery,
  useGetAdminTopicQuery,
  useGetAdminTopicsQuery,
  useUpdateAdminQuizOptionMutation,
  useUpdateAdminQuizQuestionMutation,
  useUpdateAdminScenarioMutation,
  useUpdateAdminScenarioOptionMutation,
  useUpdateAdminScenarioStepMutation,
  useUpdateAdminTheoryBlockMutation,
  useUpdateAdminTopicMutation,
} from './api/adminContentApi'
export { statusLabels } from './model/statusLabels'
export type {
  AdminQuizOption,
  AdminQuizQuestion,
  AdminScenario,
  AdminScenarioDraft,
  AdminScenarioOption,
  AdminScenarioStep,
  AdminTheoryBlock,
  AdminTopic,
  AdminTopicDraft,
  ContentStatus,
  OptionPoints,
  ResponseType,
  TheoryKind,
} from './model/types'
